title: Basics of NLP
description: >
  Cleaning text, lemmatization, stopword removal, and overcoming NLP challenges.
logo: /assets/Kiyaalva.png
remote_theme: pages-themes/cayman
plugins:
- jekyll-remote-theme

github:
  is_project_page: true
