theme: jekyll-theme-minimal
title: "Basics of NLP"
description: "Cleaning text, lemmatization, stopword removal, and overcoming NLP challenges."
logo: /assets/Kiyaalva.png  
github:
  is_project_page: true